{% set version = "3.5.1" %}

package:
  name: preact-cli
  version: {{ version }}

source:
  url: https://registry.npmjs.org/preact-cli/-/preact-cli-{{ version }}.tgz
  sha256: 029392799c88e65b2004c6569c7046fafa6547c83e4df265ad8a4675d95ba173

build:
  number: 0
  skip: True  # [win or nodejs != 20]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
    - nodejs
    - pnpm
    - pnpm-licenses
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - preact --help

about:
  license: MIT
  license_file:
    - LICENCE
    - third-party-licenses.txt
  summary: Your next Preact PWA starts in 30 seconds.
  home: https://github.com/preactjs/preact-cli
  dev_url: https://github.com/preactjs/preact-cli

extra:
  recipe-maintainers:
    - danielnachun
